=== department-of-veterans-affairs/vets-api/modules/appeals_api/config/schemas/v2/10182_headers.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "description": "JSON Schema for Notice of Disagreement Creation endpoint headers (Decision Reviews API)",
  "$ref": "#/definitions/nodCreateParameters",
  "definitions": {
    "nonBlankString": {
      "type": "string",
      "pattern": "[^ \\f\\n\\r\\t\\v\\u00a0\\u1680\\u2000-\\u200a\\u2028\\u2029\\u202f\\u205f\\u3000\\ufeff]",
      "$comment": "The pattern used ensures that a string has at least one non-whitespace character. The pattern comes from JavaScript's \\s character class. \"\\s Matches a single white space character, including space, tab, form feed, line feed, and other Unicode spaces. Equivalent to [ \\f\\n\\r\\t\\v\\u00a0\\u1680\\u2000-\\u200a\\u2028\\u2029\\u202f\\u205f\\u3000\\ufeff].\": https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Character_Classes  We are using simple character classes at JSON Schema's recommendation: https://tools.ietf.org/html/draft-handrews-json-schema-validation-01#section-4.3"
    },

    "date": { "type": "string", "pattern": "^[0-9]{4}(-[0-9]{2}){2}$", "minLength": 10, "maxLength": 10 },

    "nodCreateParameters": {
      "type": "object",
      "properties": {
        "X-VA-First-Name":      { "$ref": "#/definitions/X-VA-First-Name" },
        "X-VA-Middle-Initial":  { "$ref": "#/definitions/X-VA-Middle-Initial" },
        "X-VA-Last-Name":       { "$ref": "#/definitions/X-VA-Last-Name" },
        "X-VA-File-Number":     { "$ref": "#/definitions/X-VA-File-Number" },
        "X-VA-Birth-Date":      { "$ref": "#/definitions/X-VA-Birth-Date" },
        "X-VA-Claimant-First-Name":     { "$ref": "#/definitions/X-VA-Claimant-First-Name" },
        "X-VA-Claimant-Middle-Initial": { "$ref": "#/definitions/X-VA-Claimant-Middle-Initial" },
        "X-VA-Claimant-Last-Name":      { "$ref": "#/definitions/X-VA-Claimant-Last-Name" },
        "X-VA-Claimant-Birth-Date":     { "$ref": "#/definitions/X-VA-Claimant-Birth-Date" },
        "X-Consumer-Username":  { "$ref": "#/definitions/X-Consumer-Username"},
        "X-Consumer-ID":        { "$ref": "#/definitions/X-Consumer-ID"}
      },
      "dependencies": {
        "X-VA-Claimant-First-Name": ["X-VA-Claimant-Last-Name", "X-VA-Claimant-Birth-Date"],
        "X-VA-Claimant-Middle-Initial": ["X-VA-Claimant-First-Name", "X-VA-Claimant-Last-Name"],
        "X-VA-Claimant-Last-Name": ["X-VA-Claimant-First-Name"],
        "X-VA-Claimant-Birth-Date": ["X-VA-Claimant-Last-Name"]
      },
      "required": [
        "X-VA-First-Name",
        "X-VA-Last-Name",
        "X-VA-File-Number",
        "X-VA-Birth-Date"
      ]
    },

    "X-VA-First-Name": {
      "type": "string",
      "description": "Veteran's first name",
      "minLength": 1,
      "maxLength": 255,
      "$comment": "can be whitespace, to accommodate those with 1 legal name"
    },

    "X-VA-Middle-Initial": {
      "allOf": [
        { "description": "Veteran's middle initial", "minLength": 1, "maxLength": 1 },
        { "$ref": "#/definitions/nonBlankString" }
      ]
    },

    "X-VA-Last-Name": {
      "allOf": [
        { "description": "Veteran's last name", "minLength": 1, "maxLength": 255 },
        { "$ref": "#/definitions/nonBlankString" }
      ]
    },

    "X-VA-Birth-Date": {
      "allOf": [
        { "description": "Veteran's birth date" },
        { "$ref": "#/definitions/date" }
      ]
    },

    "X-VA-Claimant-First-Name": {
      "type": "string",
      "description": "Non-Veteran claimant's first name",
      "minLength": 1,
      "maxLength": 255,
      "$comment": "can be whitespace, to accommodate those with 1 legal name"
    },

    "X-VA-Claimant-Middle-Initial": {
      "allOf": [
        { "description": "Non-Veteran claimant's middle initial", "minLength": 1, "maxLength": 1 },
        { "$ref": "#/definitions/nonBlankString" }
      ]
    },

    "X-VA-Claimant-Last-Name": {
      "allOf": [
        { "description": "Non-Veteran claimant's last name", "minLength": 1, "maxLength": 255 },
        { "$ref": "#/definitions/nonBlankString" }
      ]
    },

    "X-VA-Claimant-Birth-Date": {
      "allOf": [
        { "description": "Non-Veteran claimant's birth date" },
        { "$ref": "#/definitions/date" }
      ]
    },

    "X-VA-File-Number": {
      "allOf": [
        { "description": "Veteran's VA file number (c-file / css)", "minLength": 1, "maxLength": 9 },
        { "$ref": "#/definitions/nonBlankString" }
      ]
    },

    "X-Consumer-Username": {
      "allOf": [
        { "description": "Consumer Username (passed from Kong)", "minLength": 1, "maxLength": 255 },
        { "$ref": "#/definitions/nonBlankString" }
      ]
    },

    "X-Consumer-ID": {
      "allOf": [
        { "description": "Consumer GUID", "minLength": 1, "maxLength": 255 },
        { "$ref": "#/definitions/nonBlankString" }
      ]
    }
  }
}

=== department-of-veterans-affairs/vets-api/modules/appeals_api/spec/fixtures/v2/valid_10182_headers_extra.json
{
  "X-VA-First-Name": "Jäñe",
  "X-VA-Middle-Initial": "Z",
  "X-VA-Last-Name": "Doe",
  "X-VA-File-Number": "987654321",
  "X-VA-Birth-Date": "1969-12-31",
  "X-VA-Claimant-Birth-Date": "1972-05-08",
  "X-VA-Claimant-First-Name": "Betty",
  "X-VA-Claimant-Middle-Initial": "D",
  "X-VA-Claimant-Last-Name": "Boop",
  "X-Consumer-Username": "va.gov",
  "X-Consumer-ID": "some-guid"
}
